'use strict';

module.exports = {
  MAX_OSPATH: 260,
  MAX_SPLITSCREEN_CLIENTS: 2,
  MAX_PLAYER_NAME_LENGTH: 128,
  SIGNED_GUID_LEN: 32,
  MAX_CUSTOM_FILES: 4,
  SUBSTRING_BITS: 5,
  MAX_USERDATA_BITS: 14,
  MAX_EDICT_BITS: 11,
  NUM_NETWORKED_EHANDLE_SERIAL_NUMBER_BITS: 10
}
