'use strict';

const MAX_EDICT_BITS = 11;
const NETWORKED_EHANDLE_ENT_ENTRY_MASK = (1 << MAX_EDICT_BITS) - 1;
const NUM_NETWORKED_EHANDLE_SERIAL_NUMBER_BITS = 10;
const NUM_NETWORKED_EHANDLE_BITS = MAX_EDICT_BITS + NUM_NETWORKED_EHANDLE_SERIAL_NUMBER_BITS;

module.exports = {
  MAX_OSPATH: 260,
  MAX_SPLITSCREEN_CLIENTS: 2,
  MAX_PLAYER_NAME_LENGTH: 128,
  SIGNED_GUID_LEN: 32,
  MAX_CUSTOM_FILES: 4,
  SUBSTRING_BITS: 5,
  MAX_USERDATA_BITS: 14,
  MAX_EDICT_BITS,
  NETWORKED_EHANDLE_ENT_ENTRY_MASK,
  NUM_NETWORKED_EHANDLE_SERIAL_NUMBER_BITS,
  NUM_NETWORKED_EHANDLE_BITS,
  INVALID_NETWORKED_EHANDLE_VALUE: (1 << NUM_NETWORKED_EHANDLE_BITS) - 1
};
