name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages (npm ci)
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - name: Check code style
        run: npx run format:check
      - name: Lint code
        run: npm run lint
      - name: Run tests
        run: npm test
