name: Documentation

on:
  push:
    branches: [master]

jobs:
  docs:
    name: Generate Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Generate documentation
        run: npm run generate-docs
      - name: Push back to GitHub
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add -A docs/
          git commit -m "Update documentation"
          git push
